"""add abc field in admin

Revision ID: 53ae8c76e1f4
Revises: ff2d153c0539
Create Date: 2026-02-17 16:12:55.989272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ae8c76e1f4'
down_revision: Union[str, Sequence[str], None] = 'ff2d153c0539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('abc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'abc')
    # ### end Alembic commands ###
