"""remove abc  field in admin

Revision ID: 831d3eefa0a9
Revises: 53ae8c76e1f4
Create Date: 2026-02-17 16:14:25.605844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831d3eefa0a9'
down_revision: Union[str, Sequence[str], None] = '53ae8c76e1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'abc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('abc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
