"""Add nullable teacher name field in course model

Revision ID: eb8c717a521e
Revises: 831d3eefa0a9
Create Date: 2026-02-18 17:05:06.352588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8c717a521e'
down_revision: Union[str, Sequence[str], None] = '831d3eefa0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher_name')
    # ### end Alembic commands ###
