"""initial migration

Revision ID: ff2d153c0539
Revises: 
Create Date: 2026-02-17 16:11:15.618019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2d153c0539'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'assignments', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'attendence', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'attendence', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.alter_column('admins', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
